DefCon-Apps/DefCon-FE

src/Common/BackgroundCard.tsx

페이지 디자인에 사용 될 사각형 모양의 컴포넌트를 추가했습니다.
```typescript
import BackgroundCard from "../../src/Common/BackgroundCard";
```
```html
<BackgroundCard 
color="#004477"  
height="18rem" 
translateX="-40%" 
translateY="50%" 
type="filled" 
/>
```

[ADD]BackgroundCard 컴포넌트 추가

---

pages/Main/MainAwards.tsx
pages/Main/MainHistory.tsx
pages/Main/MainRectangle.tsx
pages/Main/MainWorks.tsx
src/Common/BackgroundCard.tsx
styles/globals.css

- @rdg1029 제작의 BackgroundCard 컴포넌트를 활용하여 Main 페이지에 Rectangle 디자인 요소 추가
- 지난 PR에서 제기되었던 문제인 MainWorks 컴포넌트의 Margin 단위 이슈 해결
- BackgroundCard 컴포넌트의 Props 중 type의 형을 'bordered' || 'filled' 에서 string으로 수정
- MainRectangle 컴포넌트에 Main 페이지에 들어갈 Rectangle들이 가져야할 속성으로 이루어진 배열을 정의하여 BackgroundCard 컴포넌트를 리스트 렌더링하여 구현하였음.
- MainRectangle 컴포넌트의 BackgroundCard의 단위는 동적이어야 하므로 rem을 사용하였으나 테스트 배포시 문제 발생하면 변경해야할 소지가 있음.

Main 페이지에 Rectangle 디자인 추가

---

package-lock.json
package.json
pages/Projects/Projects.tsx
pages/Projects/[ProjectDetail].tsx
src/Common/API.ts

Projects, ProjectDetail 페이지에 API를 적용했습니다.
- API.ts 파일에 데이터 타입 정의
- API.ts 파일에 getProjectData() & getProjectList() 추가
- 프로젝트 상세 페이지에 API 데이터 & react-markdown 모듈 적용
- 프로젝트 페이지에 카테고리 별로 임시 리스트 적용
- 프로젝트 페이지에 적용할 리스트 컴포넌트 제작 예정
- CORS 때문에 제대로 나오는지 아직 확인 못 한 상태

[UPDATE] 프로젝트 페이지 기본 API 연동 작업

---

pages/Projects/Projects.tsx

Project 페이지의 Project Item 렌더링 시 누락된 Key Props를 추가하였습니다.
각 Project Item Data의 id값을 참조하여 Key Props로 적용하고자 하였으나, 원인 불명의 Type Error가 발생하여 map 과정에서 index 값을 추가로 받고, 이를 Key Props로 구현하였습니다.

[FIX] Project 페이지 API 연동 관련 Build 불가 이슈

---

pages/Projects/ProjectList.tsx
pages/Projects/ProjectListItem.tsx
pages/Projects/ProjectSection.tsx
pages/Projects/Projects.tsx
src/Common/API.ts

가로 방향으로 스크롤 되는 프로젝트 목록을 만들었습니다.
- 무한으로 Item 추가 되는 문제 해결
- ProjectListItem 컴포넌트 생성
- ProjectList 컴포넌트 생성
- Projects 페이지에 ProjectList 적용
프로젝트 목록은 아래 사진과 같이 나옵니다.

[UPDATE] 프로젝트 페이지에 목록 추가

---

pages/Projects/ProjectList.tsx

`TypeError: Cannot read properties of undefined (reading 'map')`
빌드를 할 때 리스트에서 map 속성을 찾지 못하는 오류를 수정했습니다.
이렇게 나오면 빌드 잘 된거 맞죠?

[FIX] Project List 관련 빌드 오류 수정

---

pages/Members/Members.tsx
pages/Members/MembersListItem.tsx
pages/Members/MembersRectangle.tsx
src/Common/BackgroundCard.tsx

- Members 각 카드 클릭시 Rectangle 박스를 보여줍니다.
- Members 각 카드 마우스 오버시 그림자 효과를 보여줍니다.
- Members 각 카드 클릭시 내용이 보여질 공간을 위해 마진을 부여합니다.
- Members 카드 클릭시 Rectangle 박스에 CSS 속성 Width를 Props로 부여하기 위해 BackgroundCard.tsx를 단일 styled-component에서 컴포넌트를 함수로 선언하는 것으로 수정하였습니다.
- defaultProps 속성을 선언하여 width가 Props를 통해 넘겨지지 않을 시에는 기존과 동일한 width를 유지하도록 했습니다.
- 위에서 수정한 BackgroundCard 컴포넌트에 width 속성을 Props로 넘겨주어 멤버 디테일을 보여줄 박스를 보여줍니다.
- 이 박스는 isFirstClicked를 이름으로 갖는 Bool 타입 State의 상태에 따라 보여줄지 말지 결정됩니다. 
- :hover에 Box-Shadow 속성을 추가하여 마우스 오버시 그림자 효과를 보여줍니다. 그림자의 색상은 이번 웹의 메인 테마 색상으로 설정했습니다.
- 멤버 별 각 카드 클릭시 내용 및 박스가 보여질 공간을 위해 isFirstClicked State의 상태에 따라 마진을 부여합니다.

[UPDATE] Members 페이지 부가 디자인 요소 적용

---

pages/Members/MembersListItem.tsx
pages/Members/MembersRectangle.tsx
pages/Members/MembersTitle.tsx

- 요청하신 수정 사항을 반영하였습니다.
- MembersRectangle의 translate 속성을 viewport 단위로 조정하여 px 단위로 적용했을 때와 동일한 위치를 적용했습니다.
- width와 height에 사용된 rem 단위는 다시 한 번 테스트 서버 배포 결과를 보고 수정 유무를 판단하고 싶어 유지하였습니다.
- MembersListItem에 적용된 마우스 hover시 box-shadow 속성을 부여하는 효과를 transition 속성을 이용하여 부드럽게 조정하였습니다. (그림자가 생기는 속도가 마음에 안들면 수정하겠습니다.)
- MembersTitle에서 letter-spacing 속성을 부여하여 자간을 조절하였고 line-height 속성을 조정하여 행간을 조절하였습니다.
- sub title에 font-weight 속성을 300으로 부여하여 Figma 프로토타입과 동일한 디자인 형태를 적용하였습니다.

[FIX] Member 페이지 디자인 세부사항 개선 완료

---

pages/Members/Members.tsx
pages/Members/MembersDetail.tsx
pages/Members/MembersList.tsx
pages/Members/MembersListItem.tsx
pages/Members/MembersTitle.tsx
pages/Projects/ProjectListItem.tsx
pages/Projects/ProjectSection.tsx
pages/Projects/[ProjectDetail].tsx
src/Common/ImageSlider.tsx

프로젝트 페이지와 멤버 페이지에 모바일 UI를 적용했습니다.
- 프로젝트 목록 페이지에 모바일 화면 대응
- 프로젝트 상세 페이지에 모바일 화면 대응
- 멤버 페이지에 모바일 화면 대응
- 멤버 아이템 클릭시 멤버 상세 정보 부분으로 화면 자동 스크롤
(너비 1024px 미만일 경우 제목, 부제목이 가운데로 정렬됩니다.)
(멤버 클릭시 화면 스크롤이 상세 정보 부분까지 내려갑니다.)

[UPDATE] 프로젝트 페이지, 멤버 페이지 모바일 UI 적용

---

pages/Members/MembersDetail.tsx
pages/Projects/ProjectListItem.tsx
src/Common/ImageSlider.tsx

멤버 페이지 관련 빌드 오류를 해결하고 프로젝트 페이지에서 전반적으로 사용한 img 태그를 next/imge로 변경했습니다.
- forwardRef 사용시 displayName 설정 -> 빌드 오류 원인
- ProjectListItem 컴포넌트에서 img 대신 next/image 사용
- ImageSlider 컴포넌트에서 img 대신 next/image 사용

[FIX] 멤버 페이지 관련 빌드 오류 해결

---

pages/Main/MainHistory.tsx
pages/Main/MainTitle.tsx
pages/Main/MainWorks.tsx

- Main 페이지 내 Title, History, Awards, Works 네 개의 섹션에 대한 모바일 UI 구현
- 768px 기준으로 적용
- react-responsive 라이브러리의 useMediaQuery Hook을 활용하여 구현

[UPDATE] Main Mobile UI Layout

---

pages/Main/MainAwards.tsx
pages/Main/MainHistory.tsx
pages/Main/MainTitle.tsx
pages/Main/MainWorks.tsx
pages/Members/Members.tsx
src/Common/Footer.tsx
src/Common/Header.tsx

- Member 페이지와 동일하게 1208px 기준의 미디어 쿼리를 styled-component에 적용하여 반응형을 구현하였습니다.
- 그에 따라 기존에 반응형 구현을 위해 사용한 react-responsive 라이브러리의 useMediaQuery Hook의 사용을 최대한 지양하여 코드를 수정하였습니다.
- 작동은 기존 768px을 기준으로 모바일/데스크탑을 구현했던 때보다 훨씬 자연스러워졌습니다.
- 싹 갈아엎느라 힘든 관계로 Design 페이지는 기상 후에 해드리겠습니다.
- 이상 전달 끝

[FIX] Main Mobile UI : useMediaQuery Hook 사용 최소화

---

pages/Main/MainAwards.tsx
pages/Main/MainTitle.tsx
src/Common/BackgroundCard.tsx

react-hydration 관련 오류 & 모바일 화면에서 오른쪽 여백이 생기는 문제 해결
- useMediaQuery를 사용하는 컴포넌트에 state를 하나씩 추가했습니다.
- **BackgroundCard**가 모바일 화면에서 문제를 일으키던 원인이었습니다.  
- BackgroundCard의 `position:absoulte` 때문에 대참사가 일어났던 것 같습니다.
- 너비가 1280px 미만일 경우 BackcgroundCard의 display를 none으로 설정했습니다.

[FIX] react-hydration 관련 오류 & 모바일 화면 여백 문제

---

pages/Main/MainAwards.tsx
pages/Main/MainHistory.tsx

- 각 섹션 타이틀을 이루는 구역에 width를 % 단위로 지정하였습니다.
- macOS 해상도 옵션 중 "추가 공간" 에서도 이상 없이 작동하는 것을 확인하였습니다.
- 모바일에서는 기존 버전과 동일하게 작동합니다.
MainAwards 섹션의 타이틀이 고장나보이는 것은 배경 사각형을 고려하여 텍스트 색상을 흰색으로 지정했기 때문입니다.
텍스트 색상을 검은색으로 통일하거나 배경의 사각형을 조정하면 해결될 문제입니다.

[FIX] Main 페이지 레이아웃 오류 수정

---

pages/Designs/CrabIntro.tsx
pages/Designs/LogoIntro.tsx

- LogoIntro 섹션 구조 리팩토링
- CrabIntro 섹션 CSS 속성 조정
- 이전 PR에서 발생한 Designs 페이지 레이아웃 오류 해결
- LogoIntro 섹션에서 margin 으로 조악하게 잡혀있던 레이아웃을 CSS flex 속성으로 변경
- 그에 따른 컴포넌트 계층 구조 수정
- CrabIntro 섹션은 단순히 CSS 속성만 조정하여 해결
- max-width: 768px 대응 추가
- Description 부분의 width를 % -> vw 단위로 조정하여 해결

[FIX] Designs 페이지 레이아웃 오류 수정

---

.babelrc
pages/Main/MainAwards.tsx
pages/Main/MainTitle.tsx

메인 페이지에서 새로고침시 컴포넌트가 왼쪽으로 이동하는 문제를 개선했습니다.
- MainTitle 컴포넌트에서 paragraph의 width 속성 제거
- babelrc 파일 추가
- MainTitle 컴포넌트에서 isDesktop의 기본 값을 true로 설정
- MainAwards 컴포넌트에서 isDesktop의 기본 값을 true로 설정
#64 관련 코드를 작성한 이후 발생한 문제인 것 같습니다.

[FIX] 메인 페이지 새로고침 문제 개선

---

package-lock.json
package.json
pages/Projects/[ProjectDetail].tsx

- Project Detail 페이지 내, Markdown 렌더링 컴포넌트를 구현하였습니다.
- 기존에 적용되어있던 `React Markdown` 라이브러리를 이어서 활용하였습니다.
- `Rehype Raw` 플러그인을 추가해, HTML 렌더링을 활성화하였습니다.
- `Remark GFM` 플러그인을 추가해, 리스트 및 테이블 렌더링을 활성화하였습니다.
- 기존에 지속적으로 발생하던 개행 이슈의 경우, 개행문자를 Escape 처리에서 제외하는 방식을 채택해 해결하였습니다. Firebase Firestore에 게시글 데이터 저장 시, `\n`으로 개행을 표시하면, 내부적으로 `\\n`으로 자동 변환되는데, 이를 다시 렌더링 과정에서 `\n`으로 치환하도록 하였습니다.

[DEV] Project 페이지 MD Renderer 개선

---

pages/Main/MainAwards.tsx
pages/Main/MainHistory.tsx

- #92 에서 제시된 개선점을 개선하였습니다.
- MainHistory, MainAwards 섹션을 담당하여 작업하였습니다.
- 모바일 UI 레이아웃의 MediaQuery를 조정하였습니다.
- MainAwards에서 불필요한 useMediaQuery Hook을 제거하여 CSS MediaQuery로 변경하였습니다.
- 컴포넌트의 위치를 변경하는 조건부 렌더링을 제거하였습니다.
- 모바일 UI 레이아웃에서 애매한 768px ~ 1024px 사이의 속성을 추가하였습니다.
- 불필요한 Wrapper, Container를 제거하며 전반적인 컴포넌트 계층구조를 개선하였습니다.

[FIX] Main 페이지 디테일 개선 1

---

pages/Main/MainTitle.tsx
pages/Main/MainWorks.tsx

MainTitle 컴포넌트의 데스크탑 기준 너비를 변경하고, MainWorks의 가로 스크롤 리스트를 개선했습니다.
- MainTitle, MainWorks에서 데스크탑 기준 너비를 1280px로 설정
- MainWorks에서 ScrollMenuWrapper의 스타일 수정
- 모바일 화면에서도 가로 스크롤이 가능할 것으로 예상

[FIX] Main 페이지 디테일 개선 2

---

pages/Main/MainWorks.tsx

[FIX] MainWorks 타이틀 위치 조정

---

pages/Main/MainAwards.tsx

- Main 페이지엑서 API 호출이 무한정 반복되던 문제를 해결하였습니다.
- Main 페이지의 MainAwards 컴포넌트에서 사용된 useEffect Hook이 원인이었습니다.
- Dependency 없이 useEffect Hook이 정의되어있었고, 그로인해 State가 변경되는 시점마다 재귀적으로 Hook이 작동하였고, 그로 인해서 불필요하게 과도한 API 트래픽이 발생하였습니다.
- 해당 useEffect Hook에 Empty Dependency를 적용하여 문제를 해결하였습니다.

[FIX] Main 페이지 API 호출 Leak

---

pages/Members/MembersDetail.tsx

우측 데이터 박스의 높이를 좌측 카드 리스트와 동일하게 설정했습니다.
- 데이터 박스의 height를 780px로 설정
- overflow-y -> scroll로 적용

[DEV] Member 페이지 우측 데이터 박스 높이 조정

---

pages/Projects/ProjectListItem.tsx
src/Common/ImageSlider.tsx

- Project 페이지에서 이미지가 정상적으로 렌더링되지 않는 문제를 해결하였습니다.
- Project List 페이지에서 Project의 대표 이미지와, Project Detail 페이지에서 Project 상세 이미지들이 정상적으로 렌더링되지 않고 있었습니다.
- `Base64 String` 형식으로 이미지를 정의하였으나, 내부 코드에서 `URL` 형식으로 이미지를 렌더링 시도하여 찾지 못하는 문제가 발생했습니다.
- 해당하는 부분을 모두 `Base64 String` 형식으로 수행하도록 개선하였습니다.

[FIX] Project 페이지 이미지 렌더링 불가

---

pages/Main/MainAwards.tsx
pages/Main/MainHistory.tsx
pages/Main/MainTitle.tsx
pages/Main/MainWorks.tsx

- 중구난방이었던 CSS 속성을 가다듬었습니다.
- 디자인 요소 Rectangle을 삭제하였습니다.
- MainAward 섹션에 데이터를 추가하였습니다.
- min-width 기준으로 잡혀있던 media query를 iPad Air (820 * 1180), iPhone XR (414 * 896) max-width를 기준으로 하여 작성하였습니다.
- 화면에 따라 유연하게 적용되도록 폰트 및 마진 단위에서 pt, px 사용을 지양하고 rem 및 뷰포트 단위로 가다듬었습니다.
- MainAwards 데이터가 빈곤하길래 데이터를 삽입하여 UI를 다시 가다듬었습니다.

[FIX] Main 페이지 CSS 리팩토링

---

pages/Projects/[ProjectDetail].tsx

- Projects 상세 보기 페이지의 CSS 스타일을 리팩토링하였습니다.
- 다음과 같은 화면 너비 기준으로 미디어 쿼리를 작성하였습니다.
- 1280px 이상 - 데스크탑 기준
- 1024px ~ 1279px - 노트북 & 태블릿 가로 화면 기준
- 768px ~ 1023px - 태블릿 가로 화면 기준
- 480px ~ 767px - 모바일 가로 & 태블릿 세로 화면 기준
- ~ 479px - 기타 모바일 세로 화면 기준
- 요청대로 너비를 px 단위로 고정 후 자식 요소들에 대한 크기는 em및 % 단위를 활용하여 반응형으로 동작할 수 있도록 구성하였습니다.
- 크기는 LGTM인데 맘에 안들면 말하지 마세요. 히히
- 자세한 상태는 첨부한 이미지를 확인해주세요.

[FIX] Projects 상세 보기 페이지 CSS 스타일 리팩토링

---

pages/Main/MainAwards.tsx
pages/Main/MainHistory.tsx
pages/Main/MainTitle.tsx
pages/Main/MainWorks.tsx

- Main 페이지의 CSS 스타일의 리팩토링을 리팩토링하였습니다.
- Projects 상세보기 페이지와 동일한 Media Query 기준을 적용하였습니다.
- 다음과 같은 화면 너비 기준으로 미디어 쿼리를 작성하였습니다.
- 1280px 이상 - 데스크탑 기준
- 1024px ~ 1279px - 노트북 & 태블릿 가로 화면 기준
- 768px ~ 1023px - 태블릿 가로 화면 기준
- 480px ~ 767px - 모바일 가로 & 태블릿 세로 화면 기준
- ~ 479px - 기타 모바일 세로 화면 기준
- 전반적인 폰트와 이미지 크기를 조정하였습니다. 
- 이 기준 역시 LGTM입니다.
- 자세한 변경사항은 첨부한 이미지를 통해 확인해주세요.

[FIX] Main 페이지 CSS 스타일 리팩토링

---

pages/Projects/Projects.tsx

Project List에서 항목이 누락되던 이슈를 해결하였습니다.
- 기존 코드의 경우, 각 Category별 List가 State로 선언되어있고, API에서 불러온 데이터를 map으로 선회하며 List State에 Append 하도록 되어있었습니다.
- 여기서, 비동기로 동작하는 State의 특성으로 인해 새 데이터가 Append되기 직전 빈 List State에 반복해서 Append 되는 현상이 일어나, 최종적으로는 가장 마지막 항목만이 유일하게 List에 포함되는 문제가 원인이었습니다.
- `useEffect` 내에서 임시 List를 생성하고, API에서 불러온 데이터를 선회하며 이 임시 List에 데이터를 Append한 뒤, 최종적으로 1회만 List State에 지정하는 방식으로 해결하였습니다.

[FIX] Project List 항목 누락 이슈 해결

---

pages/Projects/ProjectSection.tsx
pages/Projects/Projects.tsx

프로젝트 페이지에서 리스트들의 간격을 조정했습니다.
- ProjectSection의 width 값 조정
- ProjectSection에서 padding-top 적용 (96px, width 768px 미만 -> 64px)
- Project 페이지에서 margin-top 적용 (128px)
해상도 : 1920x1080
해상도 : iPhone 12 Pro

[FIX] ProjectList 간격 조정

---

pages/main/Index.tsx
pages/main/index.tsx

#138 이후로 Build가 불가하던 문제를 해결하였습니다.
- Main Page의 `index.tsx` 및 `Index.tsx`가 중복되어 발생하던 문제를 해결하였습니다.

[FIX] Build Error 해결

---

pages/projects/ProjectListItem.tsx
pages/projects/Projects.tsx

- Projects List 페이지 전체 하단 여백을 부여하였습니다.
- Projects List에서 각 아이템별 title을 삭제하였습니다.
- 각 아이템에서 border-radius 속성을 제거하였습니다.
- overfit : cover 속성을 제거하였습니다.
- 이건 별개인데 현재 업로드 되어있는 항목에 대한 썸네일을 적용하였습니다.

[FIX] Project List 페이지 개선사항 반영

---

pages/projects/Projects.tsx

- #142 Issues에 주어져있던 태스크 중 Projects List를 최신순으로 보여주기 위해 반전하는 것이 누락되어 작업하였습니다.
- pages/projects/Projects.tsx에서 비동기 요청으로 요청한 list 형태의 자료를 setState 할 때 reverse() 메소드를 활용하여 반전된 상태로 변경되도록 하였습니다.
- 추후에 등록된 TAXI METER 및 MILICENSE가 먼저 표시됩니다.

[FIX] ProjectList Reverse
