DefCon-Apps/DefCon-FE

- .gitignore
- Dockerfile
- Jenkinsfile
- Node 16.17.0 기반의 Docker 빌드 환경을 설정하였습니다.
- Docker 빌드 및 Dockerhub 배포를 수행하는 Jenkins 환경을 설정하였습니다.
> [ADD] Docker 및 Jenkins 환경설정

- pages/_document.tsx
- pages/index.tsx
> [ISSUE] index.tsx 및 _document.tsx 오류 해결

- pages/index.tsx
- index.tsx 내 Main import 구문 오류를 해결하였습니다.
> [FIX] index.tsx 오류 해결

- Dockerfile
- next.config.js
- Dockerfile에서 Builder과 Runner을 분리하였습니다.
- Next Config에 Standalone 옵션을 지정하였습니다.
> [FIX] Docker 빌드 Issue 해결 시도

- package-lock.json
- package.json
- pages/Projects/ProjectSection.tsx
- pages/Projects/Projects.tsx
- pages/Projects/[ProjectDetail].tsx
- src/Common/BackgroundCard.tsx
- src/Common/ImageSlider.tsx
프로젝트 페이지와 상세 페이지 기본 레이아웃을 구성했습니다.
- BackgroundCard.tsx 파일 들여쓰기 간격 조정
- ProjectSection 컴포넌트 생성 후 Project 페이지에 적용
- ProjectDetail 페이지 레이아웃 구성
- 이미지 슬라이더 제작을 위해  [react-slick](https://react-slick.neostack.com/) 모듈 사용
- ImageSlider 컴포넌트 생성 후 ProjectDetail 페이지에 적용
프로젝트 페이지
프로젝트 상세 정보 페이지
> [ADD] Project 페이지 레이아웃 구성

- pages/Members/MembersDetail.tsx
- pages/Members/MembersList.tsx
- pages/Members/MembersListItem.tsx
특정 Issue로 인해 Jenkins에서 빌드가 진행되지 않는 문제를 해결하였습니다.
Image의 경우, Next에서 제공하는 Component를 활용하도록 변경하였습니다. 해당 Component의 경우, Alt Props가 필요하여 추가적으로 정의해주었습니다.
Dynamic으로 렌더링하는 Iterator 방식 List 렌더링 과정에, 각 Item에 대한 Key 값을 추가 구현하였습니다.
> [FIX] 긴급 빌드 불가 해결

- pages/Main/MainAwards.tsx
- pages/Main/MainHistory.tsx
- src/Common/API.ts
- styles/globals.css
- @yymin1022 와 같이 디코를 통한 코딩으로 문제를 해결하였읍니다.
- 더 이상의 설명은 생략한다. 라고 할 뻔
- [https://github.com/DefCon-Apps/DefCon-BE/blob/master/API.md](url)
- 위 문서에 따라 API를 호출하였음.
- useState, useEffect Hook을 사용하여 데이터를 동적으로 사용할 수 있게 하였음.
- 겸사겸사 rem을 검거해서 pt로 정신개조 시켜주었음.
> [UPDATE] MainAwards 파트 API 연동 완료

- pages/Main/MainAwards.tsx
- pages/Main/MainHistory.tsx
- pages/Main/MainWorks.tsx
- Main 페이지를 구성하고 있는 각 컴포넌트 안에 Rectangle 컴포넌트를 삽입하였습니다.
- 위치 단위를 Viewport 단위로 잡았습니다.
> [ADD] Main 페이지 Rectangle 삽입 완료

- styles/globals.css
Dark Mode 관련 구문을 비활성화하였습니다.
```global.css```에서 Dark Mode 관련 Media-Query Styling을 비활성화하여, Dark-Mode 설정에 의존하지 않고 Light-Mode가 기본적으로 Render 되도록 하였습니다.
추후 디테일한 디자인을 다듬은 이후 Dark-Mode를 다시 Enable하도록 하겠습니다.
> [UPADTE] 다크 모드 비활성화

- pages/Designs/CrabIntro.tsx
- pages/Designs/Designs.tsx
- pages/Designs/LogoIntro.tsx
- pages/Main/MainAwards.tsx
- pages/Main/MainHistory.tsx
- pages/Main/MainTitle.tsx
- pages/Main/MainWorks.tsx
- src/Common/Header.tsx
- 일단 고백할게 있습니다. 모바일은 되는데 데스크탑이 고장났습니다. 18일 (토) 이내 해결 예정
- 헤더 또한 18일 (토) 이내 해결 예정
> [UPDATE] Designs 페이지 모바일 레이아웃 적용

- src/Common/Header.tsx
- 기존 padding, margin으로 잡혀있던 Nav와 Logo의 정렬을 flex 속성으로 수정하여 어떤 환경에서도 정렬을 유지하도록 하였습니다.
> [FIX] Header 정렬 수정

- pages/Designs/CrabIntro.tsx
- pages/Main/MainAwards.tsx
- pages/Main/MainHistory.tsx
- pages/Main/MainTitle.tsx
- pages/Main/MainWorks.tsx
- src/Common/Crab.tsx
- Main 페이지에 대한 리팩토링입니다.
- 애니메이션 효과를 적용하였습니다.
- PM 요청에 따라 백그라운드의 카드 컴포넌트는 건들지 않았습니다.
- 1280px, 768px에 대응합니다.
- float Props를 추가하여 애니메이션 적용 여부를 받습니다.
- 10px을 위, 아래로 떠있는 효과를 준 float 애니메이션을 추가하였습니다.
- 타 섹션들과 달리 font-size 속성이 px 단위로 주어져있어서 pt 단위로 수정하였습니다.
- 모바일에서의 시인성을 위해 font-size 속성을 수정하였습니다.
- Crab Logo에 float 애니메이션 Props를 true로 주어 게를 둥둥 띄웠습니다.
- Scroll Arrow에 float 애니메이션을 적용하였습니다.
-  Crab Logo에 적용된 애니메이션과 달리 위아래로 20px을 움직입니다.
- 데스크탑 버전에서 해상도에 따라 위치가 흐트러지던 오류를 수정하였습니다.
- margin 속성으로 설정되어 있던 레이아웃을 flex 속성으로 수정하였습니다.
- p 태그에 width 속성을 지정하여 레이아웃을 유지하도록 하였습니다.
- 데스크탑 버전에서 해상도에 따라 위치가 흐트러지던 오류를 수정하였습니다.
- flex 속성 적용을 위한 Container - Items 계층 구조가 잘못되어 있어 전면적으로 구조를 수정하였습니다.
- margin 속성으로 설정되어 있던 레이아웃을 flex 속성으로 수정하였습니다.
- 텍스트의 속성들을 조금 수정하였습니다.
> [FIX] Main Page Refactoring

- pages/Projects/Projects.tsx
- pages/Projects/[ProjectDetail].tsx
프로젝트 페이지와 상세 페이지에 폰트를 적용했습니다.
- 프로젝트 페이지 최상위 컴포넌트에 font-family로 폰트 적용
- 프로젝트 상세 페이지 최상위 컴포넌트에 font-family로 폰트 적용
로컬에서 돌렸을 때 모바일 크롬에서 폰트가 잘 적용된 걸 확인했지만,
배포했을 때 잘 적용이 될지 확인해봐야 할 것 같습니다.
> [FIX] 프로젝트 페이지 폰트 적용

- pages/Designs/CrabIntro.tsx
- pages/Designs/LogoIntro.tsx
- #74 에 대한 레이아웃 개선 작업입니다.
- 텍스트와 타이틀에 단순히 width 속성으로 정의되어있던 비율을 flex-basis 속성으로 변경하였습니다.
- 텍스트의 사이징을 pt 단위에서 em 단위로 변경하여 반응형 대응을 도모하였습니다.
> [FIX] Designs 페이지 레이아웃 개선

- pages/Projects/[ProjectDetail].tsx
- Project 페이지의 useEffect Hook을 개선하였습니다.
- Project 페이지에서 useEffect Hook이 Project Data State 값을 지속적으로 감지하여, 불필요한 BE 요청이 누적되는 문제를 해결하였습니다.
- Project Data State 대신 Routing을 이용해 Project ID 값을 감지하도록 하였습니다
> [FIX] Project 페이지 useEffect 불필요 감지 조건 제거

- pages/Designs/CrabIntro.tsx
기준 UI를 Desktop으로 통일시켰습니다.
- CrabIntro 컴포넌트의 기준 UI를 Desktop으로 지정
> [DEV] 반응형 기준 변경 작업

- next.config.js
- Production Build 배포 시 Project Page를 Refresh 할 경우 404 Error가 발생하는 문제를 해결합니다.
- Next Config에 TrailingSlash 옵션을 추가하고, True 값을 지정하였습니다.
> [DEV] Next 라우팅 문제 해결

- pages/Designs/CrabIntro.tsx
- pages/Designs/LogoIntro.tsx
- pages/Main/MainAwards.tsx
- pages/Main/MainHistory.tsx
- pages/Main/MainWorks.tsx
Border 타입으로 된 BackgroundCard를 제거하고 텍스트 배경에 Solid 타입의 카드 배경을 적용했습니다.
- MainHistory
- MainAwards
- MainWorks
- LogoIntro
- CrabIntro
> 위 5개 컴포넌트에서 해당 작업을 진행하고 그에 맞게 CSS 일부를 수정
> [DEV] BackgroundCard 제거 작업

- pages/Designs/CrabIntro.tsx
- pages/Main/MainTitle.tsx
- pages/Projects/ProjectListItem.tsx
- src/Common/Crab.tsx
> [FIX] Crab 컴포넌트 내 img 태그 제거

- pages/Main/MainAwards.tsx
- pages/Main/MainHistory.tsx
- #95 에 대한 개선사항.
- 모바일 UI 좌우 여백 늘려왔습니다
> [FIX] Main 페이지 디테일 개선작업 - 1

- pages/index.tsx
- Project 전역에 적용되는 Metadata 속성을 정의하였습니다.
- Project Metadata에 Title 속성을 추가하였습니다.
- Favicon의 경우, Static 페이지에서 기본적으로 정의되어있어, 따로 추가하지 않았습니다.
- ```localhost``` Dev 배포의 경우, Static으로 빌드되지 않고 배포되기 때문에, Favicon이 적용되지 않았으나, 실제 Static Public 배포시에는 정상적으로 표시됩니다.
> [DEV] Project Metadata

- pages/Designs/CrabIntro.tsx
- pages/Designs/LogoIntro.tsx
- #108 요청에 대한 작업
- 이젠 괜찮습니다.
- useMediaQuery Hook을 코드에서 제거했습니다.
- 아 그러고보니 node_modules에서 제거는 안했는데 이건 메인 PR 때 처리해드림
- SW 마에스트로 합격하게 해주세요 -> 텍데브 삼
- 모호한 해상도에 대한 대응을 추가하였습니다.
- SW마에스트로 합격하게 해주세요
> [FIX] Design 페이지 반응형 레이아웃이 박살났었는데요

- pages/Main/MainAwards.tsx
- 이제 안깨집니다.
- 소마 합격하게 해주세요.
- #108 요청에 대한 작업.
- align-items : center가 적용되는 시점을 최대 너비가 1279px인 시점까지로 확대하였습니다.
> [FIX] Main 페이지 반응형 레이아웃이 깨졌었는데요

- pages/Designs/CrabIntro.tsx
> [FIX] Designs 페이지 모바일 UI 내 Crab Logo 고장

- pages/Projects/[ProjectDetail].tsx
- pages/_document.tsx
- styles/globals.css
- Noto Sans KR 폰트를 전역적으로 적용하였습니다.
- Projets 상세보기 페이지에서 상세 내용의 폰트 사이즈가 어색해 보이는 것을 수정하였습니다.
- _document.tsx에 <link>태그를 추가하여 Noto Sans KR의 CDN을 통해 글꼴을 적용했습니다.
- globals.css에 font-family 속성을 적용하였습니다.
> [FIX] Noto Sans KR 폰트 적용

- pages/Designs/CrabIntro.tsx
- pages/Designs/Designs.tsx
- pages/Designs/LogoIntro.tsx
- pages/Main/MainAwards.tsx
- pages/_document.tsx
- Desings 페이지의 CSS 스타일을 리팩토링하였습니다.
- 다음과 같은 화면 너비 기준으로 미디어 쿼리를 작성하였습니다.
- 1280px 이상 - 데스크탑 기준
- 1024px ~ 1279px - 노트북 & 태블릿 가로 화면 기준
- 768px ~ 1023px - 태블릿 가로 화면 기준
- 480px ~ 767px - 모바일 가로 & 태블릿 세로 화면 기준
- ~ 479px - 기타 모바일 세로 화면 기준
- 자세한 사항은 첨부한 스크린샷을 참고해주세요.
> [FIX] Designs 페이지 CSS 스타일 리팩토링

- pages/designs/index.tsx
- pages/index.tsx
- pages/main/index.tsx
- pages/members/index.tsx
- pages/privacy/index.tsx
- pages/projects/index.tsx
#136 이후로 Build가 불가하던 문제를 해결하였습니다.
- 각 컴포넌트 내 `index.tsx`의 `export` 구문의 대소문자 이슈를 해결하였습니다.
> [FIX] Build Error 해결

- pages/projects/[ProjectDetail].tsx
프로젝트 상세 페이지의 이미지 슬라이더를 개선하였습니다.
- `useEffect` Hook에서 API를 통해 이미지 리스트를 받아온 직후, `splice` 함수를 이용해 0번 이미지를 제외하고 이미지 슬라이더에 전달하도록 하였습니다.
> [DEV] 프로젝트 상세 페이지 이미지 슬라이더 개선

- pages/members/Members.tsx
멤버 페이지에서 해상도 별로 설정된 너비(width 값)를 수정 수정했습니다
> [FIX] Members 페이지 너비 수정

- pages/projects/Projects.tsx
- pages/projects/[ProjectDetail].tsx
- src/Common/Loader.tsx
프로젝트 페이지에 로딩 표시를 구현했습니다.
- 프로젝트 리스트를 나타내는 페이지에서 로딩 Spinner 적용
- 프로젝트 상세 페이지에서 로딩 Spinner 적용
> [FIX] 프로젝트 페이지 로딩 표시 구현

- pages/members/Members.tsx
- pages/privacy/PrivacyContents.tsx
- pages/projects/ProjectSection.tsx
- pages/projects/[ProjectDetail].tsx
Main 페이지를 제외한 나머지 페이지들의 모바일 화면 너비를 개선했습니다.
- Members 페이지 모바일 화면 너비 수정
- Projects 페이지 모바일 화면 너비 수정
- Privacy 페이지 모바일 화면 너비 수정
> [FIX] 모바일 페이지 너비 개선

- pages/main/MainAwards.tsx
- pages/main/MainHistory.tsx
- pages/main/MainTitle.tsx
- pages/main/MainWorks.tsx
Main 페이지에 일부 개선사항을 적용하였습니다.
- 성보고 관련 항목 중, App 바로가기 링크를 수정하였습니다.
- Main 페이지의 일부 항목에 대한 반응형 문제를 해결하여 일부 기기에서 좌우가 잘리던 문제를 해결하였습니다.
> [FIX] Main 페이지 개선

- pages/designs/CrabIntro.tsx
- pages/designs/LogoIntro.tsx
- pages/main/MainTitle.tsx
- pages/members/Members.tsx
- pages/projects/ProjectSection.tsx
모바일 반응형 페이지에서 나타나는 컴포넌트 위치 문제를 해결했습니다.
- Main 페이지 타이틀 높이 수정
- Design 페이지 너비 수정
- Projects 페이지 리스트 로딩 전/후 너비 통일
- Members 페이지 높이 수정
> [FIX] 모바일 반응형 페이지 개선

- Jenkinsfile
> [DEV] Jenkins Notificator 연동
